[workspace]
members = [
  "plugins/animate-logo",
  "plugins/banner",
  "plugins/chocolatey",
  "plugins/display-resolution",
  "plugins/docker",
  "plugins/gauges",
  "plugins/github-stats",
  "plugins/langs",
  "plugins/music-player",
  "plugins/theme-detection",
  "plugins/theme-manager",
  "plugins/timezone",
  "plugins/user-info",
  "plugins/weather",
  "plugins/temperature",
  "plugins/wasm-crypto",
]
resolver = "2"

[workspace.dependencies]
xfetch-plugin-api = { version = "0.2.0", package = "xfetch-plugin-api" }
xfetch-guest-api = { version = "0.2.0", package = "xfetch-guest-api" }
